home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
]

leabharlann/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("", include("shelf.urls")),
    path("", include("books.urls")),
    path("", include("profiles.urls")),
    path("", include("mybooks.urls")),
    path("", include("myauthors.urls")),
    path("", include("mygenres.urls")),
    path("", include("sharing.urls")),
    path("", include("wanted.urls")),
    path("", include("review.urls")),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = "profiles"
urlpatterns = [
    path("profile-list/", views.profile_list, name="profile-list"),
    path("profile/<int:pk>/", views.profile_detail, name="profile-detail"),
    path("edit-profile/", views.edit_profile, name="edit-profile"),
    path(
        "toggle-profile-private/<int:pk>/",
        views.toggle_private,
        name="toggle-profile-private",
    ),
    path("friend-list/<int:pk>/", views.friend_list, name="friend-list"),
    path("invite/<int:pk>/", views.invite_friend, name="invite"),
    path(
        "friend-request-detail/<int:pk>/",
        views.friend_request_detail,
        name="friend-request-detail",
    ),
    path(
        "send-friend-request/<int:pk>/",
        views.send_friend_request,
        name="send-friend-request",
    ),
    path("friend-request-list/", views.friend_requests, name="friend-request-list"),
    path(
        "accept-friend-request/<int:pk>/",
        views.accept_friend_request,
        name="accept-friend-request",
    ),
    path(
        "reject-friend-request/<int:pk>/",
        views.reject_friend_request,
        name="reject-friend-request",
    ),
    path("unfriend/<int:pk>/", views.unfriend, name="unfriend"),
]

sharing/urls.py
from django.urls import path
from . import views


app_name = "sharing"
urlpatterns = [
    path("loaned-list/", views.loaned_list, name="loaned-list"),
    path("borrowed-list/", views.borrowed_list, name="borrowed-list"),
    path(
        "add-loaned/<int:pk>/",
        views.add_loaned,
        kwargs={"borrower_id": None},
        name="add-loaned",
    ),
    path("add-borrowed/<int:pk>/", views.add_borrowed, name="add-borrowed"),
    path("edit-loaned/<int:pk>/", views.edit_loaned, name="edit-loaned"),
    path("delete-loaned/<int:pk>/", views.delete_loaned, name="delete-loaned"),
    path("marked-returned/<int:pk>/", views.mark_returned, name="marked-returned"),
    path("request-list/", views.request_received_list, name="request-list"),
    path("request/<int:pk>/", views.request_received, name="request"),
    path(
        "request-accept/<int:pk>/", views.request_received_accept, name="request-accept"
    ),
    path(
        "request-reject/<int:pk>/", views.request_received_reject, name="request-reject"
    ),
    path("request-sent-list/", views.request_sent_list, name="request-sent-list"),
    path("request-sent/<int:pk>/", views.request_sent, name="request-sent"),
    path("request-send/<int:pk>/", views.request_send, name="request-send"),
]

shelf/urls.py
from django.urls import path
from . import views


app_name = "shelf"
urlpatterns = [
    path("my-shelf/<int:pk>", views.my_shelf, name="myshelf"),
]

wanted/urls.py
from django.urls import path
from . import views


app_name = "wanted"
urlpatterns = [
    path("wanted/<int:pk>/", views.wanted, name="wanted"),
    path("add-wanted/", views.add_wanted, kwargs={"book_id": None}, name="add-wanted"),
    path("edit-wanted/<int:pk>/", views.edit_wanted, name="edit-wanted"),
    path("delete-wanted/<int:pk>/", views.delete_wanted, name="delete-wanted"),
]

profiles/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from leabharlann.utils import edit_image


class Profile(models.Model):
    """
    Model representing a user profile.
    Fields to be displayed are user, first_name, last_name, about_me, profile_pic.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(
        max_length=50, blank=True, help_text="Optional. Enter your first name"
    )
    last_name = models.CharField(
        max_length=50, blank=True, help_text="Optional. Enter your last name"
    )
    about_me = models.TextField(
        max_length=500, blank=True, help_text="Optional. Tell us about yourself"
    )
    profile_pic = models.ImageField(
        upload_to="profile_pics",
        blank=True,
        help_text="Optional. Upload a profile picture",
    )
    joined_on = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(
        default=False,
        help_text="If checked, your profile will not be visible to other users",
    )
    friends = models.ManyToManyField(
        User,
        blank=True,
        related_name="friends",
        help_text="Select the users you want to be friends with",
    )

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        """
        Override the save method of the Profile model to resize the profile pic.
        """
        if self.profile_pic:
            self.profile_pic = edit_image(self.profile_pic, 100, 100)
        super(Profile, self).save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile.
    """
    if created:
        Profile.objects.create(user=instance)
    # Existing users: just save the profile
    instance.profile.save()


class FriendRequest(models.Model):
    """
    Model representing a friend request.
    Fields to be displayed are from_user, to_user, accepted.
    """

    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="from_user"
    )
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="to_user")
    sent = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.from_user} to {self.to_user}"

    def save(self, *args, **kwargs):
        if self.accepted:
            self.from_user.profile.friends.add(self.to_user)
            self.to_user.profile.friends.add(self.from_user)
        super(FriendRequest, self).save(*args, **kwargs)

profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    """
    Form for adding and editing profiles.
    """

    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "about_me", "profile_pic")


class InviteForm(forms.Form):
    """
    Form for inviting users to the site.
    """

    name = forms.CharField(help_text="Enter your friend's name")
    email = forms.EmailField(help_text="Enter your friend's email")

profiles/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.models import User

from .models import Profile, FriendRequest
from .forms import ProfileForm, InviteForm

from .invite_handler import handle_invite


def profile_list(request):
    """
    View function for listing all profiles.
    Returns the profiles ordered by name and the profile count.
    """
    profiles = Profile.objects.all().order_by("name")
    profile_count = profiles.count()
    context = {"profiles": profiles, "profile_count": profile_count}
    return render(request, "profiles/profile-list.html", context)


def profile_detail(request, pk):
    """
    View function for displaying a single profile.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    profile = Profile.objects.get(pk=pk)
    friends = profile.friends.all()[:5]
    friend_request = FriendRequest.objects.filter(
        to_user=pk, from_user=request.user
    ).first()
    context = {"profile": profile, "friends": friends, "friend_request": friend_request}
    return render(request, "profiles/profile.html", context)


def edit_profile(request):
    """
    View function for editing a profile.
    Passes the instance argument to the ProfileForm.
    Returns the ProfileForm to the template.
    """
    profile = Profile.objects.get(user=request.user)
    if request.user != profile.user:
        return render(request, "profiles/profile-list.html")
    else:
        if request.method == "POST":
            form = ProfileForm(request.POST, instance=profile)
            if form.is_valid():
                profile = form.save(commit=False)
                profile.save()
                messages.success(request, "Profile updated successfully")
                return redirect("profiles:profile-detail", pk=profile.pk)
            else:
                messages.error(request, "Error updating profile")
        else:
            form = ProfileForm(instance=profile)
        context = {
            "form": form,
            "object_name": "My Profile",
            "action_name": "Edit",
        }
        return render(request, "generic-form.html", context)


def toggle_private(request, pk):
    """
    View function for toggling the private status of a profile.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    profile = Profile.objects.get(pk=pk)
    profile.private = not profile.private
    profile.save()
    return redirect("profiles:profile-detail", pk=profile.pk)


def friend_list(request, pk):
    """
    View function for listing all friends.
    Returns the friends of the current user.
    """
    if request.GET:
        query = request.GET.get("search")
        if query:
            results = User.objects.filter(username__icontains=query, private=False)
            context = {
                "results": results,
                "query": query,
            }
            return render(request, "profiles/friend-list.html", context)

    profile = Profile.objects.get(user=pk)
    friends = profile.friends.all()
    context = {"friends": friends}
    return render(request, "profiles/friend-list.html", context)


def invite_friend(request, pk):
    """
    View function for sending an email to invite a friend outside the site.
    """

    if request.method == "POST":
        handle_invite(request, pk, request.POST.get("name"), request.POST.get("email"))
        messages.success(request, "Invitation sent")
        return HttpResponse(status=204)

    form = InviteForm()
    context = {
        "form": form,
        "modal_title": "Invite a friend",
        "button_label": "Send invitation",
    }
    return render(request, "modal/modal-form.html", context)


def send_friend_request(request, pk):
    """
    View function for sending a friend request.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    to_user = User.objects.get(pk=pk)
    friend_request, created = FriendRequest.objects.get_or_create(
        from_user=request.user, to_user=to_user
    )
    if created:
        messages.success(request, "Friend request sent")
    else:
        messages.error(request, "You have already sent a friend request to this user")
    return redirect("profiles:profile-detail", pk=pk)


def friend_requests(request):
    """
    View function for listing all friend requests.
    Returns the friend requests of the current user.
    """
    friend_requests = FriendRequest.objects.filter(to_user=request.user, accepted=False)
    context = {"friend_requests": friend_requests}
    return render(request, "profiles/friend-request-list.html", context)


def friend_request_detail(request, pk):
    """
    View function for displaying a single friend request.
    Returns the friend request object with the primary key (pk) equal to the pk argument.
    """
    friend_request = FriendRequest.objects.get(pk=pk)
    context = {"friend_request": friend_request}
    return render(request, "modal/friend-request.html", context)


def accept_friend_request(request, pk):
    """
    View function for accepting a friend request.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    if request.method == "POST":
        friend_request = FriendRequest.objects.get(pk=pk)
        friend_request.accepted = True
        friend_request.save()
        messages.success(request, "Friend request accepted")
        return HttpResponse(status=204)
    else:
        messages.error(request, "Error accepting friend request")


def reject_friend_request(request, pk):
    """
    View function for rejecting a friend request.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    if request.method == "POST":
        friend_request = FriendRequest.objects.get(pk=pk)
        friend_request.delete()
        messages.success(request, "Friend request rejected")
        return HttpResponse(status=204)
    else:
        messages.error(request, "Error rejecting friend request")


def unfriend(request, pk):
    """
    View function for removing a friend.
    Returns the profile object with the primary key (pk) equal to the pk argument.
    """
    profile = Profile.objects.get(pk=pk)
    profile.friends.remove(request.user)
    request.user.profile.friends.remove(profile.user)
    messages.success(request, "Friend removed")
    return redirect("profiles:profile-detail", pk=pk)

profiles/templates/profiles/friend-list.html
{% extends "base.html" %}

{% load static %}

{% block title %}Friend List{% endblock %}

{% block content %}

<section class="container">
    <div class="d-flex flex-row justify-content-evenly align-items-center book-shadow">
        <a class="btns" href="{{request.META.HTTP_REFERER}}"><i class="fa-solid fa-arrow-left"></i> Go back</a>
        <a class="btns" href="{% url 'profiles:friend-request-list' %}">Friend Requests</a>        
    </div>
    <div>
        <h2 class="text-center">Find Friends</h2>
        <form method="GET" action="{% url 'profiles:friend-list' user.pk %}" class="d-flex flex-row">
            <input class="form-control" type="text" name="search" placeholder="Search by username" />
            <button class="btns" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        <p>Have a friend who hasn't joined yet?</p>
        <a class="btns"
            data-hx-get="{% url 'profiles:invite' user.pk %}"
            data-hx-target="#dialog">Invite A Friend</a>
    </div>
</section>
{% if query %}
<section>
    <h2 class="text-center">Search Results</h2>
    {% for result in results %}
    <div>
        <div>
            <a class="links" href="{% url 'profiles:profile-detail' result.profile.id %}">{{ result }}</a>
        </div>
    </div>
    <hr/>
    {% empty %}
    <p>No users found.</p>
    {% endfor %}
</section>
{% endif %}
<section class="container">
    <h1 class="text-center">Friends List</h1>

    {% for friend in friends %}
    <div>
        <div>
            <a class="links" href="{% url 'profiles:profile-detail' friend.profile.id %}">{{ friend }}</a>
            <a href="{% url 'profiles:unfriend' friend.profile.id %}" class="btns-cancel"><i class="fa-solid fa-user-minus"></i> Remove Friend</a>
        </div>
    </div>
    <hr/>
    {% empty %}
    <p>No friends found.</p>
    {% endfor %}
</section>

{% endblock %}
<!-- Modal JS-->
{% block extra_js %}
<script src="{% static 'js/modal.js' %}"></script>
{% endblock %}

profiles/templates/profiles/friend-request-list.html
{% extends "base.html" %}

{% load static %}

{% block title %}Friends Requests{% endblock %}

{% block content %}
<section class="container">
  <a class="btns" href="{{request.META.HTTP_REFERER}}"><i class="fa-solid fa-arrow-left"></i> Go back</a>
{% for request in friend_requests %}
<div>
  <div>
    <a class="links"
      href="{% url 'profiles:profile-detail' request.from_user.id %}">{{ request.from_user }}</a>
    wants to be friends.
    <a class="btns"
    data-hx-get="{% url 'profiles:friend-request-detail' pk=request.pk %}"
    data-hx-target="#dialog">View</a>
  </div>
</div>
<hr/>
{% empty %}
<p>No friend requests</p>
{% endfor %}    
</section>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/modal.js' %}"></script>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}

<!-- Load static -->
{% load static %}

<!-- Page title -->
{% block title %}
{% if user == profile.user %}
    My Profile
    {% else %}
    {{ profile.user }}'s Profile
    {% endif %}
{% endblock title %}

<!-- Page content -->
{% block content %}

<!-- Profile -->
<section class="container">
    <h1 class="text-center">
        {% if user == profile.user %}
        My Profile
        {% else %}
        {{ profile.user }}'s Profile
        {% endif %}
    </h1>
    <div class="col-12 col-md-10 d-flex flex-row flex-wrap mx-auto">
        <div class="col-12 col-md-8 px-3">
            <div class="d-flex flex-col book-shadow">
                {% if profile.profile_pic %}
                <img class="img-fluid profile-pic" src="{{ profile.profile_pic.url }}" alt="{{ profile.user }}">
                {% else %}
                <img class="img-fluid profile-pic" src="{% static 'images/user.png' %}" alt="{{ profile.user }}">
                {% endif %}
            </div>
            <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Username:</th>
                    <td>{{ profile.user }}</td>
                </tr>
                <tr>
                    <th>First Name:</th>
                    <td>
                        {% if profile.first_name == '' %}
                        <i>Not set</i>
                        {% else %}
                        {{ profile.first_name }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Last Name:</th>
                    <td>
                        {% if profile.last_name == '' %}
                        <i>Not set</i>
                        {% else %}
                        {{ profile.last_name }}
                        {% endif %}
                    </td>   
                </tr>
                <tr>
                    <th>Joined:</th>
                    <td>{{ profile.joined_on|date:"d M Y" }}</td>
                </tr>
            </table>                
            </div>

            <div>
                <h3>
                    About
                    {% if user == profile.user %}
                    Me
                    {% else %}
                    {{ profile.user }}
                    {% endif %}
                </h3>
                {% if profile.about_me %}
                <p>{{ profile.about_me }}</p>
                {% else %}
                <p><i>Not set</i></p>
                {% endif %}
            </div>
            {% if user == profile.user %}
            <a class="btns" href="{% url 'profiles:edit-profile' %}"><i class="fa-solid fa-user-pen"></i> Edit Profile</a>
            {% endif %}
        </div>
        <div class="col-12 col-md-4 px-3">
            {% if user == profile.user %}
            <div class="mb-2">
                <h2>Privacy</h2>
                {% if profile.private %}
                <p class="mt-4">Your profile is private</p>
                <a class="btns" href="{% url 'profiles:toggle-profile-private' profile.pk %}"><i class="fa-solid fa-eye"></i> Make Public</a>
                {% else %}
                <p class="mt-4">Your profile is public</p>
                <a class="btns" href="{% url 'profiles:toggle-profile-private' profile.pk %}"><i class="fa-solid fa-eye-slash"></i> Make Private</a>
                {% endif %}                
            </div>
            <div class="mb-2">
                <h2>Loan Requests</h2>
                <a class="links" href="{% url 'sharing:request-list' %}"><i class="fa-solid fa-envelope"></i> Requests</a>
            </div>
            {% else %}
            <div class="mb-2">
                {% if user in profile.friends.all %}
                    <p>You are friends with {{ profile.user }}</p>
                    <a class="btns" href="{% url 'profiles:unfriend' profile.user.pk %}"><i class="fa-solid fa-user-minus"></i> Remove Friend</a>
                {% elif friend_request.sent %}
                    <p>You have sent a friend request to {{ profile.user }}</p>
                {% else %}
                    <p>You are not friends with {{ profile.user }}</p>
                    <a class="btns" href="{% url 'profiles:send-friend-request' profile.user.pk %}"><i class="fa-solid fa-user-plus"></i> Send Friend Request</a>
                {% endif %}
            </div>
            {% endif %}
            <div class="d-flex flex-column">
                <a href="{% url 'shelf:myshelf' profile.user.id %}" class="links">
                    View 
                    {% if user == profile.user %}
                    My
                    {% else %}
                    {{ profile.user }}'s
                    {% endif %}
                    Shelf
                </a>
                <a href="{% url 'wanted:wanted' profile.user.id %}" class="links">
                    View 
                    {% if user == profile.user %}
                    My
                    {% else %}
                    {{ profile.user }}'s
                    {% endif %}
                    Wanted Books
                </a>
            </div>
            <div class="book-shadow d-flex flex-column">
            <h2 class="text-center"><i class="fa-solid fa-user-group"></i> Friends</h2>
                {% for friend in friends %}
                <p>
                    <a class="links" href="{% url 'profiles:profile-detail' friend.profile.pk %}">{{ friend }}</a>
                </p>
                {% empty %}
                <p>
                    <i>No friends yet</i>
                </p>
                {% endfor %}
                <a href="{% url 'profiles:friend-list' profile.user.id %}" class="links">View All Friends</a> <!-- Link to list of friends --> <!-- Also want a way to send a friend request -->
                {% if user == profile.user %}
                <a href="{% url 'profiles:friend-request-list' %}" class="links">Friend Requests</a>
                {% endif %}             
            </div>
        </div>
    </div>
</section>

{% endblock %}