books/urls.py
from django.urls import path
from . import views


app_name = "books"
urlpatterns = [
    path("author-list/", views.author_list, name="author-list"),
    path("author/<int:pk>/", views.author_detail, name="author-detail"),
    path("add-author/", views.add_author, name="add-author"),
    path("edit-author/<int:pk>/", views.edit_author, name="edit-author"),
    path("book-list/", views.book_list, name="book-list"),
    path("book/<int:pk>/", views.book_detail, name="book-detail"),
    path("add-book/", views.add_book, name="add-book"),
    path("edit-book/<int:pk>/", views.edit_book, name="edit-book"),
    path("genre-list/", views.genre_list, name="genre-list"),
    path("genre/<int:pk>/", views.genre_detail, name="genre-detail"),
    path("add-genre/", views.add_genre, name="add-genre"),
    path("edit-genre/<int:pk>/", views.edit_genre, name="edit-genre"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
]

leabharlann/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("", include("shelf.urls")),
    path("", include("books.urls")),
    path("", include("profiles.urls")),
    path("", include("mybooks.urls")),
    path("", include("myauthors.urls")),
    path("", include("mygenres.urls")),
    path("", include("sharing.urls")),
    path("", include("wanted.urls")),
    path("", include("review.urls")),
]

myauthors/urls.py
from django.urls import path

from . import views

app_name = "myauthors"
urlpatterns = [
    path("myauthors/<int:pk>/", views.my_authors, name="myauthors"),
    path(
        "myauthor-detail/<int:pk>/<int:user_id>/",
        views.myauthor_detail,
        name="myauthor-detail",
    ),
    path(
        "add-myauthor/",
        views.add_myauthor,
        kwargs={"author_id": None},
        name="add-myauthor",
    ),
    path("add-myauthor/<int:author_id>/", views.add_myauthor, name="add-myauthor"),
    path("edit-myauthor/<int:pk>/", views.edit_myauthor, name="edit-myauthor"),
    path("delete-myauthor/<int:pk>/", views.delete_myauthor, name="delete-myauthor"),
]

mybooks/urls.py
from django.urls import path
from . import views


app_name = "mybooks"
urlpatterns = [
    path("mybooks/<int:pk>", views.my_books, name="mybooks"),
    path("mybook-detail/<int:pk>/", views.mybook_detail, name="mybook-detail"),
    path("add-mybook/", views.add_mybook, kwargs={"book_id": None}, name="add-mybook"),
    path("add-mybook/<int:book_id>/", views.add_mybook, name="add-mybook"),
    path("edit-mybook/<int:pk>/", views.edit_mybook, name="edit-mybook"),
    path("start-reading/<int:pk>/", views.start_reading, name="start"),
    path("update-progress/<int:pk>/", views.update_progress, name="update-progress"),
    path("update-notes/<int:pk>/", views.update_notes, name="update-notes"),
    path("update-summary/<int:pk>/", views.update_summary, name="update-summary"),
    path("mark-finished/<int:pk>/", views.mark_finished, name="finish"),
    path("mark-abandoned/<int:pk>/", views.mark_abandoned, name="abandon"),
    path("toggle-favourite/<int:pk>/", views.toggle_favourite, name="favourite"),
    path("toggle-private/<int:pk>/", views.toggle_private, name="private"),
    path("delete-book/<int:pk>/", views.delete_mybook, name="delete-book"),
]

mygenres/urls.py
from django.urls import path
from . import views

app_name = "mygenres"
urlpatterns = [
    path("mygenres/<int:pk>/", views.my_genres, name="mygenres"),
    path(
        "mygenre-detail/<int:pk>/<int:user_id>/",
        views.mygenre_detail,
        name="mygenre-detail",
    ),
    path(
        "add-mygenre/", views.add_mygenre, kwargs={"genre_id": None}, name="add-mygenre"
    ),
    path("add-mygenre/<int:genre_id>/", views.add_mygenre, name="add-mygenre"),
    path("edit-mygenre/<int:pk>/", views.edit_mygenre, name="edit-mygenre"),
    path("delete-mygenre/<int:pk>/", views.delete_mygenre, name="delete-mygenre"),
]

books/forms.py
from django import forms

from .models import Author, Book, Genre


class AuthorForm(forms.ModelForm):
    """
    Form for adding and editing authors.
    """

    class Meta:
        model = Author
        fields = ["honorific", "first_name", "middle_name", "last_name"]


class BookForm(forms.ModelForm):
    """
    Form for adding and editing books.
    """

    author_first = forms.CharField(max_length=100, required=False)
    author_last = forms.CharField(max_length=100, required=False)
    new_genre = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Book
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields["author"].required = False
        self.fields["author_first"].label = "New author first name"
        self.fields["author_last"].label = "New author last name"
        self.fields["new_genre"].label = "New genre"

    def clean(self):
        cleaned_data = super(BookForm, self).clean()
        existing_author = cleaned_data.get("author")
        new_author_first = cleaned_data.get("author_first")
        new_author_last = cleaned_data.get("author_last")
        new_author = None
        if existing_author and new_author_first and new_author_last:
            raise forms.ValidationError(
                "You can't select an existing author and enter a new author"
            )
        if not existing_author and not new_author_first and not new_author_last:
            raise forms.ValidationError(
                "You must select an existing author or enter a new author"
            )
        if new_author_first and new_author_last:
            new_author = Author.objects.filter(
                first_name=new_author_first, last_name=new_author_last
            ).first()
            if new_author:
                raise forms.ValidationError("Author already exists")
            else:
                new_author = Author.objects.create(
                    first_name=new_author_first, last_name=new_author_last
                )
        if existing_author:
            cleaned_data["author"] = existing_author
            return cleaned_data
        elif new_author:
            cleaned_data["author"] = new_author
            return cleaned_data
        existing_genre = cleaned_data.get("genre")
        new_genre = cleaned_data.get("new_genre")
        if existing_genre and new_genre:
            raise forms.ValidationError(
                "You can't select an existing genre and enter a new genre"
            )
        if not existing_genre and not new_genre:
            raise forms.ValidationError(
                "You must select an existing genre or enter a new genre"
            )
        if existing_genre:
            cleaned_data["genre"] = existing_genre
            return cleaned_data
        elif new_genre:
            genre = Genre.objects.filter(name=new_genre).first()
            if genre:
                raise forms.ValidationError("Genre already exists")
            else:
                create_genre = Genre.objects.create(name=new_genre)
                cleaned_data["genre"] = create_genre
                return cleaned_data


class GenreForm(forms.ModelForm):
    """
    Form for adding and editing genres.
    """

    class Meta:
        model = Genre
        fields = ("name",)

books/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from myauthors.models import MyAuthor

from mybooks.models import MyBook
from mygenres.models import MyGenre

from .models import Author, Book, Genre
from .forms import AuthorForm, BookForm, GenreForm


def author_list(request):
    """
    View function for listing all authors.
    Returns the authors ordered by name.
    """
    authors = Author.objects.all().order_by("name")
    author_count = authors.count()
    query = None
    filter = None
    direction = None

    if request.GET:
        filterkey = request.GET.get("filterkey")
        if filterkey is None or filterkey == "default":
            authors = authors.order_by("-created_on")
        else:
            filterkey = filterkey.split("_")[0]
            filter = filterkey
            if filterkey == "first":
                filterkey = "first_name"
            elif filterkey == "last":
                filterkey = "last_name"
            elif filterkey == "popularity":
                filterkey = "number_shelves"
            direction = request.GET.get("filterkey")
            direction = direction.split("_")[1]
            if direction == "desc":
                filterkey = f"-{filterkey}"
            authors = authors.order_by(filterkey)

        if "search" in request.GET:
            query = request.GET.get("search")
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse("books:author-list"))
            queries = (
                Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
                | Q(name__icontains=query)
            )
            authors = authors.filter(queries)

    current_filterkey = filter + "_" + direction if filter and direction else None
    paginator = Paginator(authors, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        myauthors = MyAuthor.objects.filter(user=request.user)
        has_authors = [myauthor.author for myauthor in myauthors]

    context = {
        "page_obj": page_obj,
        "author_count": author_count,
        "current_filterkey": current_filterkey,
        "query_result": query if query else None,
        "has_authors": has_authors if request.user.is_authenticated else None,
    }
    return render(request, "books/author-list.html", context)


def author_detail(request, pk):
    """
    View function for displaying a single author.
    Returns the author object with the primary key (pk) equal to the pk argument.
    """
    author = Author.objects.get(pk=pk)
    books = Book.objects.filter(author=author)
    if request.user.is_authenticated:
        has_author = MyAuthor.objects.filter(user=request.user, author=author).first()

    context = {
        "author": author,
        "books": books,
        "has_author": has_author,
    }
    return render(request, "books/author.html", context)


def add_author(request):
    """
    View function for adding a new author.
    Passes the AuthorForm to the template.
    """
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            messages.success(request, "Author added successfully")
            return redirect("books:author-detail", pk=author.pk)
        else:
            messages.error(
                request, "There was a problem adding the author - please try again"
            )
    else:
        form = AuthorForm()
        context = {
            "form": form,
            "object_name": "An Author",
            "action_name": "Add",
        }
    return render(request, "generic-form.html", context)


def edit_author(request, pk):
    """
    View function for editing an author.
    Passes the instance argument to the AuthorForm.
    Returns the AuthorForm to the template.
    """
    author = Author.objects.get(pk=pk)
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            messages.success(request, "Author edited successfully")
            return redirect("books:author-detail", pk=author.pk)
        else:
            messages.error(
                request, "There was a problem editing the author - please try again"
            )
    else:
        form = AuthorForm(instance=author)
        context = {
            "form": form,
            "object_name": author.name,
            "action_name": "Edit",
        }
    return render(request, "generic-form.html", context)


def book_list(request):
    """
    View function for listing all books.
    Returns the books ordered by title.
    """
    books = Book.objects.all().order_by("title")
    book_count = books.count()

    query = None
    filter = None
    direction = None

    if request.GET:
        filterkey = request.GET.get("filterkey")
        if filterkey is None or filterkey == "default":
            books = books.order_by("title")
        else:
            filterkey = filterkey.split("_")[0]
            filter = filterkey
            if filterkey == "author":
                filterkey = "author__name"
            elif filterkey == "genre":
                filterkey = "genre__name"
            elif filterkey == "title":
                filterkey = "title"
            elif filterkey == "popularity":
                filterkey = "number_shelves"
            direction = request.GET.get("filterkey")
            direction = direction.split("_")[1]
            if direction == "desc":
                filterkey = f"-{filterkey}"
            books = books.order_by(filterkey)

        if "search" in request.GET:
            query = request.GET.get("search")
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse("books:book-list"))
            queries = (
                Q(title__icontains=query)
                | Q(author__name__icontains=query)
                | Q(genre__name__icontains=query)
            )
            books = books.filter(queries)

    current_filterkey = filter + "_" + direction if filter and direction else None
    paginator = Paginator(books, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        mybooks = MyBook.objects.filter(user=request.user)
        has_books = [mybook.book for mybook in mybooks]

    context = {
        "page_obj": page_obj,
        "book_count": book_count,
        "current_filterkey": current_filterkey,
        "query_result": query if query else None,
        "has_books": has_books if request.user.is_authenticated else None,
    }
    return render(request, "books/book-list.html", context)


def book_detail(request, pk):
    """
    View function for displaying a single book.
    Returns the book object with the primary key (pk) equal to the pk argument.
    """
    book = Book.objects.get(pk=pk)
    has_book = None
    if request.user.is_authenticated:
        has_book = MyBook.objects.filter(user=request.user, book=book).first()

    context = {
        "book": book,
        "has_book": has_book,
    }
    return render(request, "books/book.html", context)


def add_book(request):
    """
    View function for adding a new book.
    Sends the BookForm to the template.
    Passes the request.POST and request.FILES arguments to the BookForm.
    """
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            messages.success(request, "Book added successfully")
            return redirect("books:book-detail", pk=book.pk)
        else:
            messages.error(
                request, "There was a problem adding the book - please try again"
            )
    else:
        form = BookForm()
    return render(request, "books/book-form.html", {"form": form})


def edit_book(request, pk):
    """
    View function for editing a book.
    Returns the BookForm to the template.
    Returns the book object with the primary key (pk) equal to the pk argument.
    """
    book = Book.objects.get(pk=pk)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            if Book.objects.filter(title=book.title, author=book.author).exists():
                messages.error(
                    request,
                    "This book already exists - please check the list of books or try again with a different title or author",
                )
                return redirect("book-list")
            else:
                book.save()
                messages.success(request, "Book edited successfully")
                return redirect("books:book-detail", pk=book.pk)
        else:
            messages.error(
                request, "There was a problem editing the book - please try again"
            )
    else:
        form = BookForm(instance=book)
        context = {
            "form": form,
            "object_name": book.title,
            "action_name": "Edit",
        }
    return render(request, "generic-form.html", context)


def genre_list(request):
    """
    View function for listing all genres.

books/templates/books/author-list.html
{% extends "base.html" %}

<!-- Title -->
{% block title %}Authors{% endblock %}

<!-- Page content -->
{% block content %}

<!-- Quick Links-->
<div class="container">
  <h1 class="text-center">Authors</h1>
  <div class="d-flex flex-column flex-sm-row justify-content-evenly align-items-center book-shadow">
    <a class="links mb-2 mb-sm-0" href="{% url 'home:index' %}"
      ><i class="fa-solid fa-arrow-left"></i>
      Home
    </a>
    {% if user.is_authenticated %}
    <a class="btns mb-2 mb-sm-0" href="{% url 'books:add-author' %}"><i class="fa-solid fa-plus"></i> Add Author</a>
    {% endif %}

    <form method="GET" action="{% url 'books:author-list' %}" class="d-flex flex-row">
      <input
        class="form-control"
        type="text"
        name="search"
        placeholder="Search by name">
      <button class="btns" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
  </div>
</div>

<!-- Author list -->
<section class="container">
    <div>
        <h2 class="text-center">Author List</h2>
        <p>Number of authors: {{ author_count }}</p>
    </div>
    <!-- Filtering -->
    <div class="sorter d-flex flex-row justify-content-end">
        <form method="GET" action="{% url 'books:author-list' %}">
            <select
            class="form-select"
            name="filterkey"
            id="filterkey"
            onchange="this.form.submit();"
            >
            <option value="default" {% if not current_filterkey %}selected{% endif %}>Filter by</option>
            <option value="first_asc" {% if current_filterkey == 'first_asc' %}selected{% endif %}>
                First Name (A-Z)
            </option>
            <option value="first_desc" {% if current_filterkey == 'first_desc' %}selected{% endif %}>
                First Name (Z-A)
            </option>
            <option value="last_asc" {% if current_filterkey == 'last_asc' %}selected{% endif %}>
                Last Name (A-Z)
            </option>
            <option value="last_desc" {% if current_filterkey == 'last_desc' %}selected{% endif %}>
                Last Name (Z-A)
            </option>
            <option value="popularity_asc" {% if current_filterkey == 'popularity_asc' %}selected{% endif %}>
                Popularity (Low-High)
            </option>
            <option value="popularity_desc" {% if current_filterkey == 'popularity_desc' %}selected{% endif %}>
                Popularity (High-Low)
            </option>
            </select>
        </form>
    </div>
    <!-- The list -->
    <div class="col-12 col-md-8 mx-auto">
    {% if query_result %}
    <div>
      <p>{{ page_obj|length }} results for "{{ query_result }}":</p>
    </div>
    {% endif %}
      {% for author in page_obj %}
        <div class="mb-4">
            <a href="{% url 'books:author-detail' author.id %}">
                <h4>{{ author }}</h4>
            </a>
            {% if user.is_authenticated %}
            {% if author in has_authors %}
            <p>You have this author on your shelf.</p>
            {% else %}
            <a class="btns" href="{% url 'myauthors:add-myauthor' author_id=author.id %}">
                <i class="fa-solid fa-plus"></i> Add To My Authors
            </a>
            {% endif %}
            {% endif %}
        </div>
        {% empty %}
        <p>No authors found.</p>
    {% endfor %}        
    </div>
</section>
<!-- Pagination -->
<div class="pagination d-flex flex-row justify-content-center">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a class="links" href="?page=1">&laquo; first</a>
    <a class="links" href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a class="links" href="?page={{ page_obj.next_page_number }}">next</a>
    <a class="links" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

books/templates/books/author.html
{% extends "base.html" %}

{% block title %}
{{ author.name }}
{% endblock %}

{% block content %}
<section class="container">
    <div class="d-flex flex-row justify-content-evenly book-shadow">
        <a class="links" href="{% url 'books:author-list' %}">
            <i class="fa-solid fa-user-pen"></i>
            Back To Authors
        </a>
        <a class="links" href="{% url 'books:book-list' %}">
            <i class="fa-solid fa-book"></i>
            Books
        </a>
        <a class="links" href="{% url 'books:genre-list' %}">
            <i class="fa-solid fa-bookmark"></i>
            Genres
        </a>
    </div>
</section>
<section class="container">
    <div class="row">
        <div class="col-12 col-sm-8 mx-auto">
            <h1 class="text-center">{{ author.name }}</h1>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <h2>Shelves</h2>
                    <p>On {{author.number_shelves}} {% if author.number_shelves > 1 %}shelves{% else %}shelf{% endif %}.
                    </p>
                    <h2>Reads</h2>
                    <p>Read {{ author.number_reads }} time{% if author.number_reads == 1 %}{% else%}s{% endif %}.</p>
                </div>
                <div class="col-12 col-lg-6">
                    <h2>Books By {{author}}</h2>
                    <ul>
                        {% for book in books %}
                        <li><a class="links" href="{% url 'books:book-detail' book.id %}">{{ book.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% if user.is_authenticated %}
<section class="container d-flex flex-column">
    <h2>Your Shelf</h2>
    {% if has_author %}
    <p>You have this author on your shelf.</p>
    <a class="links" href="{% url 'myauthors:myauthor-detail' pk=has_author.id user_id=user.id %}">
        View On Shelf</a>
    {% else %}
    <p>You don't have this author on your shelf.</p>
    <a class="btns" href="{% url 'myauthors:add-myauthor' author.id %}">
        Add To Shelf</a>
    {% endif %}
    <a class="links" href="{ url 'shelf:myshelf' user.pk %}">
        Go To Your Shelf</a>
</section>
{% endif %}
{% endblock %}
```

books/templates/books/book.html
{% extends "base.html" %}

<!-- Load static -->
{% load static %}

<!-- Page title -->
{% block title %}{{ book.title }}{% endblock title %} {% block content %}

<!-- Quick links-->
<section class="container">
  <div class="d-flex flex-row justify-content-evenly book-shadow">
    <a class="links" href="{% url 'books:book-list' %}">
      <i class="fa-solid fa-book"></i>
      Back To Books
    </a>
    <a class="links" href="{% url 'books:author-list' %}">
      <i class="fa-solid fa-user-pen"></i>
      Authors
    </a>
    <a class="links" href="{% url 'books:genre-list' %}">
      <i class="fa-solid fa-bookmark"></i>
      Genres
    </a>
  </div>
</section>
<section class="container">
  <div class="row">
    <div class="col-12 col-sm-8 mx-auto">
      <h1 class="text-center">{{ book.title }}</h1>
      <div class="row">
        <div class="col-12 col-lg-6">
          {% if book.book_cover %}
          <img class="book-cover" src="{{ book.book_cover.url }}" alt="{{ book.title }}" />
          {% else %}
          <img class="book-cover" src="{% static 'images/plain-cover.png' %}" alt="{{ book.title }}" />
          {% endif %}
        </div>
        <div class="col-12 col-lg-6">
          <h2>Author</h2>
          <p>{{ book.author }}</p>
          <h2>Genre</h2>
          <p>
            {% for genre in book.genre.all %}{{ genre|join:", " }}
            {%empty %}No genre {% endfor %}
          </p>
          <h2>Shelves</h2>
          <p>On {{ book.number_shelves}} shelves</p>
          <h2>Reads</h2>
          <p>Read {{ book.number_reads }} times</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% if user.is_authenticated %}
<section class="container d-flex flex-column">
  <h2>Your Shelf</h2>
  {% if has_book %}
  <p>You have this book on your shelf.</p>
  <a class="links" href="{% url 'mybooks:mybook-detail' has_book.id %}">View your book</a>
  {% else %}
  <p>You don't have this book on your shelf.</p>
  <a class="btns" href="{% url 'mybooks:add-mybook' book_id=book.id %}">Add To Shelf</a>
  {% endif %}
  <a class="links" href="{% url 'shelf:myshelf' user.pk %}">Go to your shelf</a>
</section>
{% endif %} {% endblock %}

books/templates/books/genre-list.html
{% extends "base.html" %}

<!-- Title -->
{% block title %}Genres{% endblock %}

<!-- Page content -->
{% block content %}

<!-- Quick Links-->
<div class="container">
  <h1 class="text-center">Genres</h1>
  <div class="d-flex flex-column flex-md-row justify-content-evenly align-items-center book-shadow">
    <a class="links mb-2 mb-md-0" href="{% url 'home:index' %}"><i class="fa-solid fa-arrow-left"></i>
      Home
    </a>
    {% if user.is_authenticated %}
    <a class="btns mb-2 mb-md-0" href="{% url 'books:add-genre' %}"><i class="fa-solid fa-plus"></i> Add Genre</a>
    {% endif %}

    <form method="GET" action="{% url 'books:genre-list' %}" class="d-flex flex-row">
      <input class="form-control" type="text" name="search" placeholder="Search by name">
      <button class="btns" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
  </div>
</div>

<!-- Genre list -->
<section class="container">
  <div>
    <h2 class="text-center">Genre List</h2>
    <p>Number of genres: {{ genre_count }}</p>
  </div>

  <!-- Filtering -->
  <div class="sorter d-flex flex-row justify-content-end">
    <form method="GET" action="{% url 'books:genre-list' %}">
      <select class="form-select" name="filterkey" id="filterkey" onchange="this.form.submit();">
        <option value="default" {% if not current_filterkey %}selected{% endif %}>Filter by</option>
        <option value="name_asc" {% if current_filterkey == 'name_asc' %}selected{% endif %}>
          Name (A-Z)
        </option>
        <option value="name_desc" {% if current_filterkey == 'name_desc' %}selected{% endif %}>
          Name (Z-A)
        </option>
        <option value="popularity_asc" {% if current_filterkey == 'popularity_asc' %}selected{% endif %}>
          Popularity (Low-High)
        </option>
        <option value="popularity_desc" {% if current_filterkey == 'popularity_desc' %}selected{% endif %}>
          Popularity (High-Low)
        </option>
      </select>
    </form>
  </div>
  <!-- The list -->
  <div class="col-12 col-md-8 mx-auto"> 
    {% if query_result %}
    <div>
      <p>{{ page_obj|length }} results for "{{ query_result }}":</p>
    </div>
    {% endif %}
    {% for genre in page_obj %}
    <div class="mb-4">
      <a href="{% url 'books:genre-detail' genre.id %}">
        <h4>{{ genre }}</h4>
      </a>
      {% if user.is_authenticated %}
      {% if genre in has_genres %}
      <p>You have this genre on your shelf.</p>
      {% else %}
      <a class="btns" href="{% url 'mygenres:add-mygenre' genre_id=genre.id %}">
        <i class="fa-solid fa-plus"></i> Add To My Genres
      </a>
      {% endif %}
      {% endif %}
    </div>
    {% empty %}
    <p>No genres found.</p>
    {% endfor %}
  </div>
</section>
<!-- Pagination -->
<div class="pagination d-flex flex-row justify-content-center">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a class="links" href="?page=1">&laquo; first</a>
    <a class="links" href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a class="links" href="?page={{ page_obj.next_page_number }}">next</a>
    <a class="links" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}