books/urls.py
from django.urls import path
from . import views


app_name = "books"
urlpatterns = [
    path("author-list/", views.author_list, name="author-list"),
    path("author/<int:pk>/", views.author_detail, name="author-detail"),
    path("add-author/", views.add_author, name="add-author"),
    path("edit-author/<int:pk>/", views.edit_author, name="edit-author"),
    path("book-list/", views.book_list, name="book-list"),
    path("book/<int:pk>/", views.book_detail, name="book-detail"),
    path("add-book/", views.add_book, name="add-book"),
    path("edit-book/<int:pk>/", views.edit_book, name="edit-book"),
    path("genre-list/", views.genre_list, name="genre-list"),
    path("genre/<int:pk>/", views.genre_detail, name="genre-detail"),
    path("add-genre/", views.add_genre, name="add-genre"),
    path("edit-genre/<int:pk>/", views.edit_genre, name="edit-genre"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
]

leabharlann/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("", include("shelf.urls")),
    path("", include("books.urls")),
    path("", include("profiles.urls")),
    path("", include("mybooks.urls")),
    path("", include("myauthors.urls")),
    path("", include("mygenres.urls")),
    path("", include("sharing.urls")),
    path("", include("wanted.urls")),
    path("", include("review.urls")),
]

mybooks/urls.py
from django.urls import path
from . import views


app_name = "mybooks"
urlpatterns = [
    path("mybooks/<int:pk>", views.my_books, name="mybooks"),
    path("mybook-detail/<int:pk>/", views.mybook_detail, name="mybook-detail"),
    path("add-mybook/", views.add_mybook, kwargs={"book_id": None}, name="add-mybook"),
    path("add-mybook/<int:book_id>/", views.add_mybook, name="add-mybook"),
    path("edit-mybook/<int:pk>/", views.edit_mybook, name="edit-mybook"),
    path("start-reading/<int:pk>/", views.start_reading, name="start"),
    path("update-progress/<int:pk>/", views.update_progress, name="update-progress"),
    path("update-notes/<int:pk>/", views.update_notes, name="update-notes"),
    path("update-summary/<int:pk>/", views.update_summary, name="update-summary"),
    path("mark-finished/<int:pk>/", views.mark_finished, name="finish"),
    path("mark-abandoned/<int:pk>/", views.mark_abandoned, name="abandon"),
    path("toggle-favourite/<int:pk>/", views.toggle_favourite, name="favourite"),
    path("toggle-private/<int:pk>/", views.toggle_private, name="private"),
    path("delete-book/<int:pk>/", views.delete_mybook, name="delete-book"),
]

sharing/urls.py
from django.urls import path
from . import views


app_name = "sharing"
urlpatterns = [
    path("loaned-list/", views.loaned_list, name="loaned-list"),
    path("borrowed-list/", views.borrowed_list, name="borrowed-list"),
    path(
        "add-loaned/<int:pk>/",
        views.add_loaned,
        kwargs={"borrower_id": None},
        name="add-loaned",
    ),
    path("add-borrowed/<int:pk>/", views.add_borrowed, name="add-borrowed"),
    path("edit-loaned/<int:pk>/", views.edit_loaned, name="edit-loaned"),
    path("delete-loaned/<int:pk>/", views.delete_loaned, name="delete-loaned"),
    path("marked-returned/<int:pk>/", views.mark_returned, name="marked-returned"),
    path("request-list/", views.request_received_list, name="request-list"),
    path("request/<int:pk>/", views.request_received, name="request"),
    path(
        "request-accept/<int:pk>/", views.request_received_accept, name="request-accept"
    ),
    path(
        "request-reject/<int:pk>/", views.request_received_reject, name="request-reject"
    ),
    path("request-sent-list/", views.request_sent_list, name="request-sent-list"),
    path("request-sent/<int:pk>/", views.request_sent, name="request-sent"),
    path("request-send/<int:pk>/", views.request_send, name="request-send"),
]

shelf/urls.py
from django.urls import path
from . import views


app_name = "shelf"
urlpatterns = [
    path("my-shelf/<int:pk>", views.my_shelf, name="myshelf"),
]

wanted/urls.py
from django.urls import path
from . import views


app_name = "wanted"
urlpatterns = [
    path("wanted/<int:pk>/", views.wanted, name="wanted"),
    path("add-wanted/", views.add_wanted, kwargs={"book_id": None}, name="add-wanted"),
    path("edit-wanted/<int:pk>/", views.edit_wanted, name="edit-wanted"),
    path("delete-wanted/<int:pk>/", views.delete_wanted, name="delete-wanted"),
]

shelf/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

from mybooks.models import MyBook
from wanted.models import Wanted


def my_shelf(request, pk):
    """
    View function for listing all books on the user's shelf.
    Returns the books the user is currently reading, books the user has finished reading,
    their wanted books, the book count, the number of books finished, and the number of wanted books.
    """
    shelf_owner = User.objects.get(pk=pk)
    mybooks = MyBook.objects.filter(user=pk).order_by("-added_on")
    currently_reading = mybooks.filter(currently_reading=True)
    recently_finished = mybooks.filter(finished=True).order_by("-finished_reading_on")[
        :5
    ]
    wanted = Wanted.objects.filter(user=pk).order_by("-added_on")[:5]
    context = {
        "shelf_owner": shelf_owner,
        "mybooks_count": mybooks.count(),
        "finished_count": mybooks.filter(finished=True).count(),
        "currently_reading": currently_reading,
        "recently_finished": recently_finished,
        "wanted": wanted,
        "wanted_count": wanted.count(),
    }
    return render(request, "shelf/myshelf.html", context)

shelf/templates/shelf/borrowed-form.html
{% extends "base.html" %}

<!-- load crispy -->
{% load crispy_forms_tags %}

<!-- Page title -->
{% block title %}Add Borrowed Book{% endblock %}

<!-- Page content -->
{% block content %}

<section class="container">
  <h1>Add {{ object_name }} To Borrowed List</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-6">{{ form.book|as_crispy_field }}</div>
      <p>Can't find the book? Add it here:</p>
      <div class="col-6">
        <input
          type="text"
          name="new_book"
          id="new_book"
          class="form-control"
          placeholder="Add Book"
        />
        <input
          type="text"
          name="author"
          id="author"
          class="form-control"
          placeholder="Add Author"
        />
        <input
          type="text"
          name="genre"
          id="genre"
          class="form-control"
          placeholder="Add Genre"
        />
      </div>
      <div class="col-6">{{ form.borrowed_from_user|as_crispy_field }}</div>
      <div class="col-6">{{ form.borrowed_from|as_crispy_field }}</div>
      <div class="col-6">{{ form.borrowed_on|as_crispy_field }}</div>
      <div class="col-6">{{ form.notes|as_crispy_field }}</div>
      <div class="col-6">{{ form.private|as_crispy_field }}</div>
    </div>
    <button type="submit" class="btn btn-primary">Add Book</button>
  </form>
</section>

{% endblock%}

shelf/templates/shelf/myshelf.html
{% extends "base.html" %} {% load static %}

<!-- Page title-->
{% block title %}My Shelf{% endblock %}

<!-- Page Content-->
{% block content %}

<section class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>My Shelf</h1>
    </div>
  </div>
</section>
<section class="container">
  <div class="col-12">
    <div class="d-flex flex-row justify-content-evenly book-shadow" id="large-nav">
      <a class="links" href="{% url 'mybooks:mybooks' pk=shelf_owner.pk %}">
        {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Books</a>
      <a class="links" href="{% url 'myauthors:myauthors' pk=shelf_owner.pk %}">
        {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Authors</a>
      <a class="links" href="{% url 'mygenres:mygenres' pk=shelf_owner.pk %}">
        {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Genres</a>
      {% if user == shelf_owner %}
      <a class="links" href="{% url 'sharing:loaned-list' %}">Loaned</a>
      <a class="links" href="{% url 'sharing:borrowed-list' %}">Borrowed</a>
      {% endif %}
    </div>
    <div id="small-nav" class="mx-auto">
      <p>
        <button id="small-nav-btn" class="links" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNav"
          aria-expanded="false" aria-controls="collapseNav">
          Links
        </button>
      </p>
      <div class="collapse" id="collapseNav">
        <div class="book-shadow d-flex flex-column">
          <a class="links" href="{% url 'mybooks:mybooks' pk=shelf_owner.pk %}">
            {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Books</a>
          <a class="links" href="{% url 'myauthors:myauthors' pk=shelf_owner.pk %}">
            {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Authors</a>
          <a class="links" href="{% url 'mygenres:mygenres' pk=shelf_owner.pk %}">
            {% if user == shelf_owner %} My {% else %} {{ shelf_owner }}'s {% endif %} Genres</a>
          {% if user == shelf_owner %}
          <a class="links" href="{% url 'sharing:loaned-list' %}">Loaned</a>
          <a class="links" href="{% url 'sharing:borrowed-list' %}">Borrowed</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% if user == shelf_owner %}
    <div class="d-flex justify-content-evenly align-items-center my-md-5">
      <h2 class="mb-0">Add To Shelf:</h2>
      <a class="btns" href="{% url 'mybooks:add-mybook' %}">Add Book</a>
    </div>
    {% endif %}
  </div>
</section>
<hr />
<section class="container">
  <div class="row d-flex flex-row flex-wrap">
    <div class="col-12 col-md-4">
      <h3><i class="fa-solid fa-book-open-reader"></i> Currently Reading:</h3>
      <hr />
      <div>
        {% for current in currently_reading %}
        <div>
          <a href="{% url 'mybooks:mybook-detail' pk=current.pk %}">
            <h4>{{ current }}</h4>
            <p>by {{ current.book.author }}</p>
            <p>Started on: {{ current.started_reading_on }}</p>
            <p class="links">View</p>
          </a>
        </div>
        <hr />
        {% empty %} {% if user == shelf_owner %}
        <p>You're not currently reading anything.</p>
        {% else %}
        <p>{{ shelf_owner }} isn't currently reading anything.</p>
        {% endif %} {% endfor %}
      </div>
    </div>
    <div class="col-12 col-md-4">
      <h3><i class="fa-solid fa-eye"></i> Wanted:</h3>
      <hr />
      <div>
        {% for wanted in wanted %}
        <div>
          <a href="{% url 'books:book-detail' pk=wanted.book.pk %}">
            <h4>{{ wanted }}</h4>
            <p>by {{ wanted.book.author }}</p>
            <p class="links">View</p>
          </a>
        </div>
        <hr />
        {% empty %} {% if user == shelf_owner %}
        <p>You don't have any books on your wanted list.</p>
        {% else %}
        <p>{{ shelf_owner }} doesn't have any books on their wanted list.</p>
        {% endif %} {% endfor %}
      </div>
      <a class="links" href="{% url 'wanted:wanted' pk=shelf_owner.pk %}">View all wanted</a>
      {% if user == shelf_owner %}
      <p class="mt-3">
        <a class="btns" href="{% url 'wanted:add-wanted' %}">Add A Book</a>
      </p>
      {% endif %}
      <p>Total wanted: {{wanted_count}}</p>
    </div>
    <div class="col-12 col-md-4">
      <h3><i class="fa-solid fa-check"></i> Recently Finished:</h3>
      <hr />
      <div>
        {% for finished in recently_finished %}
        <div>
          <a href="{% url 'mybooks:mybook-detail' pk=finished.pk %}">
            <h4>{{ finished }}</h4>
            <p>by {{ finished.book.author }}</p>
            <p>Finished on: {{ finished.finished_reading_on }}</p>
            <p class="links">View</p>
          </a>
        </div>
        <hr />
        {% empty %} {% if user == shelf_owner %}
        <p>You haven't finished any books yet.</p>
        {% else %}
        <p>{{ shelf_owner }} hasn't finished any books yet.</p>
        {% endif %} {% endfor %}
      </div>
      <p>Total finished: {{finished_count}}</p>
    </div>
  </div>
</section>

{% endblock %}

shelf/templates/shelf/shelf-form.html
{% extends "base.html" %} {% load crispy_forms_tags %}

<!-- Page title-->
{% block title %}
<!-- Render title depending on details passed by view-->
{% if edit %}Edit{% else %}Add{% endif %} {{ object_name }} {% endblock %}

<!-- Page Content-->
{% block content %}
<section class="container">
  <h1>
    {% if edit %}Edit{% else %}Add{% endif %} {{ object_name }} {% endblock %}
  </h1>
  <form method="POST">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Edit</button>
  </form>
</section>

{% endblock %}