home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faqs/", views.faqs, name="faqs"),
]

leabharlann/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("", include("shelf.urls")),
    path("", include("books.urls")),
    path("", include("profiles.urls")),
    path("", include("mybooks.urls")),
    path("", include("myauthors.urls")),
    path("", include("mygenres.urls")),
    path("", include("sharing.urls")),
    path("", include("wanted.urls")),
    path("", include("review.urls")),
]

mybooks/urls.py
from django.urls import path
from . import views


app_name = "mybooks"
urlpatterns = [
    path("mybooks/<int:pk>", views.my_books, name="mybooks"),
    path("mybook-detail/<int:pk>/", views.mybook_detail, name="mybook-detail"),
    path("add-mybook/", views.add_mybook, kwargs={"book_id": None}, name="add-mybook"),
    path("add-mybook/<int:book_id>/", views.add_mybook, name="add-mybook"),
    path("edit-mybook/<int:pk>/", views.edit_mybook, name="edit-mybook"),
    path("start-reading/<int:pk>/", views.start_reading, name="start"),
    path("update-progress/<int:pk>/", views.update_progress, name="update-progress"),
    path("update-notes/<int:pk>/", views.update_notes, name="update-notes"),
    path("update-summary/<int:pk>/", views.update_summary, name="update-summary"),
    path("mark-finished/<int:pk>/", views.mark_finished, name="finish"),
    path("mark-abandoned/<int:pk>/", views.mark_abandoned, name="abandon"),
    path("toggle-favourite/<int:pk>/", views.toggle_favourite, name="favourite"),
    path("toggle-private/<int:pk>/", views.toggle_private, name="private"),
    path("delete-book/<int:pk>/", views.delete_mybook, name="delete-book"),
]

review/urls.py
from django.urls import path
from . import views


app_name = "review"
urlpatterns = [
    path("review-list/", views.review_list, name="review-list"),
    path("book-review-list/<int:pk>/", views.book_review_list, name="book-review-list"),
    path("review/<int:pk>/", views.review_detail, name="review-detail"),
    path("add-review/<int:pk>/", views.add_review, name="add-review"),
    path("edit-review/<int:pk>/", views.edit_review, name="edit-review"),
    path("delete-review/<int:pk>/", views.delete_review, name="delete-review"),
]

sharing/urls.py
from django.urls import path
from . import views


app_name = "sharing"
urlpatterns = [
    path("loaned-list/", views.loaned_list, name="loaned-list"),
    path("borrowed-list/", views.borrowed_list, name="borrowed-list"),
    path(
        "add-loaned/<int:pk>/",
        views.add_loaned,
        kwargs={"borrower_id": None},
        name="add-loaned",
    ),
    path("add-borrowed/<int:pk>/", views.add_borrowed, name="add-borrowed"),
    path("edit-loaned/<int:pk>/", views.edit_loaned, name="edit-loaned"),
    path("delete-loaned/<int:pk>/", views.delete_loaned, name="delete-loaned"),
    path("marked-returned/<int:pk>/", views.mark_returned, name="marked-returned"),
    path("request-list/", views.request_received_list, name="request-list"),
    path("request/<int:pk>/", views.request_received, name="request"),
    path(
        "request-accept/<int:pk>/", views.request_received_accept, name="request-accept"
    ),
    path(
        "request-reject/<int:pk>/", views.request_received_reject, name="request-reject"
    ),
    path("request-sent-list/", views.request_sent_list, name="request-sent-list"),
    path("request-sent/<int:pk>/", views.request_sent, name="request-sent"),
    path("request-send/<int:pk>/", views.request_send, name="request-send"),
]

shelf/urls.py
from django.urls import path
from . import views


app_name = "shelf"
urlpatterns = [
    path("my-shelf/<int:pk>", views.my_shelf, name="myshelf"),
]

mybooks/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Q

from shelf.utils import increment_book_shelf, increment_book_read
from books.models import Book
from review.models import MyBookReview
from mygenres.models import MyGenre
from myauthors.models import MyAuthor
from .models import MyBook
from .forms import (
    MyBookForm,
    MyBookEditForm,
    MyBookFinishedForm,
    MyBookNotesForm,
    MyBookProgressForm,
    MyBookStartForm,
    MyBookSummaryForm,
)


def my_books(request, pk):
    """
    View function for listing all books on the user's shelf.
    Includes search and filter functionality.
    """
    shelf_owner = User.objects.get(pk=pk)
    mybooks = MyBook.objects.filter(user=shelf_owner).order_by("book__title")
    mybooks_count = mybooks.count()

    query = None
    filter = None
    direction = None

    if request.GET:
        filterkey = request.GET.get("filterkey")
        if filterkey is None or filterkey == "default":
            mybooks = mybooks.order_by("book__title")
        else:
            filterkey = filterkey.split("_")[0]
            filter = filterkey
            if filterkey == "author":
                filterkey = "book__author__name"
            elif filterkey == "genre":
                filterkey = "book__genre__name"
            elif filterkey == "title":
                filterkey = "book__title"
            elif filterkey == "date":
                filterkey = "added_on"
            direction = request.GET.get("filterkey")
            direction = direction.split("_")[1]
            if direction == "desc":
                filterkey = f"-{filterkey}"
            mybooks = mybooks.order_by(filterkey)

        if "search" in request.GET:
            query = request.GET.get("search")
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse("mybooks:mybooks", args=[shelf_owner.id]))

            queries = (
                Q(book__title__icontains=query)
                | Q(book__author__name__icontains=query)
                | Q(book__genre__name__icontains=query)
            )
            mybooks = mybooks.filter(queries)

    current_filterkey = filter + "_" + direction if filter and direction else None
    paginator = Paginator(mybooks, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "shelf_owner": shelf_owner,
        "page_obj": page_obj,
        "mybooks_count": mybooks_count,
        "current_filterkey": current_filterkey,
    }
    return render(request, "mybooks/mybook-list.html", context)


def mybook_detail(request, pk):
    """
    View function for displaying a single book.
    Returns the book object with the primary key (pk) equal to the pk argument.
    """
    mybook = MyBook.objects.get(pk=pk)
    myreview = MyBookReview.objects.filter(user=request.user, book=mybook.book).first()
    context = {"mybook": mybook, "myreview": myreview}
    return render(request, "mybooks/mybook.html", context)


def add_mybook(request, book_id=None):
    """
    View function for adding a book to the user's shelf.
    """
    if request.method == "POST":
        form = MyBookForm(request.POST, request.FILES)
        if form.is_valid():
            mybook = form.save(commit=False)
            mybook.user = request.user
            mybook.save()
            increment_book_shelf(mybook.id)
            if not MyAuthor.objects.filter(
                user=request.user, author=mybook.book.author
            ):
                new_myauthor = MyAuthor.objects.create(
                    user=request.user, author=mybook.book.author
                )
                new_myauthor.save()
            for new_genre in mybook.book.genre.all():
                if not MyGenre.objects.filter(user=request.user, genre=new_genre):
                    new_mygenre = MyGenre.objects.create(
                        user=request.user, genre=new_genre
                    )
                    new_mygenre.save()

            messages.success(request, "Book added to your shelf")
            return redirect("mybooks:mybook-detail", pk=mybook.pk)
        else:
            messages.error(request, "There was an error adding the book to your shelf")
    else:
        if book_id:
            book = Book.objects.get(pk=book_id)
            form = MyBookForm(initial={"book": book})
        else:
            form = MyBookForm()
    return render(request, "mybooks/mybook-form.html", {"form": form})


def edit_mybook(request, pk):
    """
    View function for editing a book on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookEditForm(request.POST, instance=mybook)
        if form.is_valid():
            mybook = form.save(commit=False)
            mybook.user = request.user
            mybook.save()
            messages.success(request, "Book updated successfully")
            return redirect("mybooks:mybook-detail", pk=mybook.pk)
        else:
            messages.error(request, "There was an error updating the book")
    else:
        form = MyBookEditForm(instance=mybook)
    context = {
        "form": form,
        "object_name": mybook.book.title,
        "action_name": "Edit",
    }
    return render(request, "generic-form.html", context)


def start_reading(request, pk):
    """
    View function for marking a book as currently reading on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookStartForm(request.POST, instance=mybook)
        if form.is_valid():
            book = form.save(commit=False)
            book.currently_reading = True
            book.unread = False
            if book.finished or book.abandoned:
                book.restarted = True
                book.abandoned = False
                book.finished = False
                book.finished_reading_on = None
            book.save()
            messages.success(request, "Book marked as currently reading")
            return HttpResponse(status=204)
        else:
            messages.error(
                request, "There was an error marking the book as currently reading"
            )
    form = MyBookStartForm(instance=mybook)
    context = {
        "form": form,
        "modal_title": f"Mark {mybook.book.title} as currently reading?",
        "button_label": "Start",
    }
    return render(request, "modal/modal-form.html", context)


def update_progress(request, pk):
    """
    View function for updating the progress of a book on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookProgressForm(request.POST, instance=mybook)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            messages.success(request, "Book progress updated")
            return HttpResponse(status=204)
        else:
            messages.error(request, "There was an error updating the book progress")
    form = MyBookProgressForm(instance=mybook)
    context = {
        "form": form,
        "modal_title": f"Update progress for {mybook.book.title}",
        "button_label": "Update",
    }
    return render(request, "modal/modal-form.html", context)


def update_notes(request, pk):
    """
    View function for updating the notes of a book on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookNotesForm(request.POST, instance=mybook)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            messages.success(request, "Book notes updated")
            return HttpResponse(status=204)
        else:
            messages.error(request, "There was an error updating the book notes")
    form = MyBookNotesForm(instance=mybook)
    context = {
        "form": form,
        "modal_title": f"Update notes for {mybook.book.title}",
        "button_label": "Update",
    }
    return render(request, "modal/modal-form.html", context)


def update_summary(request, pk):
    """
    View function for updating the summary of a book on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookSummaryForm(request.POST, instance=mybook)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            messages.success(request, "Book summary updated")
            return HttpResponse(status=204)
        else:
            messages.error(request, "There was an error updating the book summary")
    form = MyBookSummaryForm(instance=mybook)
    context = {
        "form": form,
        "modal_title": f"Update summary for {mybook.book.title}",
        "button_label": "Update",
    }
    return render(request, "modal/modal-form.html", context)


def mark_finished(request, pk):
    """
    View function for marking a book as finished on the user's shelf.
    """
    mybook = MyBook.objects.get(pk=pk)
    if request.method == "POST":
        form = MyBookFinishedForm(request.POST, instance=mybook)
        if form.is_valid():
            mybook = form.save(commit=False)
            increment_book_read(pk)
            mybook.save()
            messages.success(request, "Book marked as finished")
            return HttpResponse(status=204)
        else:

mybooks/templates/mybooks/mybook-form.html
{% extends "base.html" %}

<!-- load crispy -->
{% load crispy_forms_tags %}

<!-- Page title -->
{% block title %}Add Book{% endblock %}

<!-- Page content -->
{% block content %}

<section class="container">
  <h1 class="text-center">Add A Book To Your Shelf</h1>
  {{ form.non_field_errors }}
  <form method="POST" enctype="multipart/form-data" class="d-flex flex-column">
    {% csrf_token %}
    <div class="col-12 col-lg-6 mx-auto">
      <div class="col-12">{{ form.book|as_crispy_field }}</div>
      {{ form.book.errors }}
      <!-- Add a new book -->
      <div class="accordion col-12 mb-2" id="accordionNewBook">
        <div class="accordion-item">
          <p class="accordion-header" id="headingOne">
            <button
              class="accordion-button"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseInputs"
              aria-expanded="true"
              aria-controls="collapseInputs"
            >
              Can't find the book? Add it here:
            </button>
          </p>
          <div
            id="collapseInputs"
            class="accordion-collapse collapse"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionNewBook"
          >
            <div class="accordion-body">
              {{ form.new_book|as_crispy_field }}
              <!-- Stop breaking tags-->
              {{ form.new_book.errors }}
              <!-- Stop breaking tags-->
              {{ form.author_first|as_crispy_field }}
              <!-- Stop breaking tags-->
              {{ form.author_first.errors }}
              <!-- Stop breaking tags-->
              {{ form.author_last|as_crispy_field }}
              <!-- Stop breaking tags-->
              {{ form.author_last.errors }}
              <!-- Stop breaking tags-->
              {{ form.genre|as_crispy_field }}
              <!-- Stop breaking tags-->
              {{ form.genre.errors }}
              <!-- Stop breaking tags-->
              {{ form.book_cover|as_crispy_field }}
              <!-- Stop breaking tags-->
              {{ form.book_cover.errors }}
            </div>
          </div>
        </div>
      </div>
      <div class="col-12">{{ form.pages_total|as_crispy_field }}</div>
      {{ form.pages_total.errors }}
      <div class="col-12">{{ form.pages_read|as_crispy_field }}</div>
      {{ form.pages_read.errors }}
      <div class="col-12">{{ form.summary|as_crispy_field }}</div>
      {{ form.summary.errors }}
      <div class="col-12">{{ form.unread|as_crispy_field }}</div>
      {{ form.unread.errors }}
      <div class="col-12">{{ form.started_reading_on|as_crispy_field }}</div>
      {{ form.started_reading_on.errors }}
      <div class="col-12">{{ form.currently_reading|as_crispy_field }}</div>
      {{ form.currently_reading.errors }}
      <div class="col-12">{{ form.finished_reading_on|as_crispy_field }}</div>
      {{ form.finished_reading_on.errors }}
      <div class="col-12">{{ form.notes|as_crispy_field }}</div>
      {{ form.notes.errors }}
      <div class="col-12">{{ form.favourite|as_crispy_field }}</div>
      {{ form.favourite.errors }}
      <div class="col-12">{{ form.private|as_crispy_field }}</div>
      {{ form.private.errors }}
    </div>
    <button type="submit" class="btns mx-auto">Add Book</button>
  </form>
</section>

{% endblock%}

mybooks/templates/mybooks/mybook-list.html
{% extends "base.html" %}

<!-- Load static -->
{% load static %}

<!-- Page title -->
{% block title %}
{% if user == shelf_owner %}My {% else %}{{ shelf_owner}}'s {% endif %}Shelf
{% endblock %}

<!-- Page content -->
{% block content %}
<section class="container">
  <div class="d-flex flex-column flex-md-row justify-content-evenly align-items-center book-shadow">
    {% if user == shelf_owner %}
    <a class="links mb-2 mb-md-0" href="{% url 'shelf:myshelf' user.pk %}"
      ><i class="fa-solid fa-arrow-left"></i>
      Back to My Shelf
    </a>
    <a class="btns mb-2 mb-md-0" href="{% url 'mybooks:add-mybook' %}"
      ><i class="fa-solid fa-plus"></i>
      Add Book
    </a>
    {% else %}
    <a class="links mb-2 mb-md-0" href="{% url 'shelf:shelf' shelf_owner.pk %}"
      ><i class="fa-solid fa-arrow-left"></i>
      Back to {{ shelf_owner}}'s Shelf
    </a>
    {% endif %}
    <form method="GET" action="{% url 'mybooks:mybooks' shelf_owner.pk %}" class="d-flex flex-row">
      <input
        class="form-control"
        type="text"
        name="search"
        placeholder="Search by title or author"
      />
      <button class="btns" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
  </div>
</section>
<section class="container">
  <h1 class="text-center">
    {% if user == shelf_owner %}My {% else %}{{ shelf_owner}}'s {% endif %}Shelf
  </h1>
  <div>
    <p>Total Books: {{ mybooks_count }}</p>
  </div>
  <div>
    <div class="sorter d-flex flex-row justify-content-end">
        <form method="GET" action="{% url 'mybooks:mybooks' shelf_owner.pk %}">
            <select
            class="form-select"
            name="filterkey"
            id="filterkey"
            onchange="this.form.submit();"
            >
            <option value="default" {% if not current_filterkey %}selected{% endif %}>Filter by</option>
            <option value="title_asc" {% if current_filterkey == 'title_asc' %}selected{% endif %}>
                Title (A-Z)
            </option>
            <option value="title_desc" {% if current_filterkey == 'title_desc' %}selected{% endif %}>
                Title (Z-A)
            </option>
            <option value="author_asc" {% if current_filterkey == 'author_asc' %}selected{% endif %}>
                Author (A-Z)
            </option>
            <option value="author_desc" {% if current_filterkey == 'author_desc' %}selected{% endif %}>
                Author (Z-A)
            </option>
            <option value="genre_asc" {% if current_filterkey == 'genre_asc' %}selected{% endif %}>
                Genre
            </option>
            <option value="genre_desc" {% if current_filterkey == 'genre_desc' %}selected{% endif %}>
                Genre (Z-A)
            </option>
            <option value="date_asc" {% if current_filterkey == 'date_asc' %}selected{% endif %}>
                Date Added (Oldest)
            </option>
            <option value="date_desc" {% if current_filterkey == 'date_desc' %}selected{% endif %}>
                Date Added (Newest)
            </option>
            </select>
        </form>
    </div>
  </div>
  {% for book in page_obj %}
  <div>
    <a href="{% url 'mybooks:mybook-detail' book.id %}">
      {% if book.cover %}
      <img class="book-cover" src="{{ book.cover.url }}" alt="{{ book.title }}" />
      {% else %}
      <img class="book-cover" src="{% static 'images/plain-cover.png' %}" alt="{{ book.title }}" />
      {% endif %}
      <h2>{{ book }}</h2>
      <h3>by {{ book.book.author }}</h3>
    </a>
  </div>
  {% empty %}
  <p>No books found.</p>

  {% endfor %}
</section>

<!-- Pagination -->
<div class="pagination d-flex flex-row justify-content-center">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a class="links" href="?page=1">&laquo; first</a>
    <a class="links" href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a class="links" href="?page={{ page_obj.next_page_number }}">next</a>
    <a class="links" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

mybooks/templates/mybooks/mybook.html
{% extends "base.html" %}

<!-- Load static -->
{% load static %}

<!-- Page title -->
{% block title %}{{ mybook.book.title }}{% endblock %}

<!-- Page content -->
{% block content %}

<section class="container">
  <div class="d-flex flex-column flex-sm-row justify-content-evenly align-items-center book-shadow">
    {% if user == mybook.user %}
    <a class="links mb-2 mb-sm-0" href="{% url 'shelf:myshelf' user.pk %}"><i class="fa-solid fa-arrow-left"></i>
      Back to My Shelf
    </a>
    <a class="links mb-2 mb-sm-0" href="{% url 'mybooks:edit-mybook' mybook.id %}"><i class="fa-solid fa-pencil"></i>
      Edit Book
    </a>
    <a class="links" href="{% url 'mybooks:delete-book' mybook.id %}"><i class="fa-solid fa-trash"></i>
      Remove Book
    </a>
    {% else %}
    <a class="links mb-2 mb-sm-0" href="{% url 'shelf:shelf' pk=shelf_owner.pk %}"><i
        class="fa-solid fa-arrow-left"></i>
      Back to {{ mybook.user}}'s Shelf
    </a>
    <a class="links" href="{% url 'sharing:request-send' mybook.id %}">
      <i class="fa-solid fa-envelope"></i>
      Request to Borrow
    </a>
    {% endif %}
  </div>
</section>
<section class="container row mx-auto">
  <div class="col-12 col-md-8 d-flex flex-column align-items-center mt-5">
    <div>
      {% if mybook.book.cover %}
      <img class="book-cover" src="{{ mybook.book.cover.url }}" alt="{{ mybook.book.title }}" />
      {% else %}
      <img class="book-cover" src="{% static 'images/plain-cover.png' %}" alt="{{ mybook.book.title }}" />
      {% endif %}
    </div>
    <div>
      <h1>{{ mybook.book.title }}</h1>
      <h2>by {{ mybook.book.author }}</h2>
      <p>
        Genre: {% for genre in mybook.book.genre.all %}{{ genre|join:", " }}
        <!-- If no genre -->
        {%empty %}No genre {% endfor %}
      </p>
    </div>
    <div class="my-2">
      <!-- Favourite book-->
      {% if mybook.favourite %}
      <p><i class="fa-solid fa-heart"></i> Favourite</p>
      {% if user == mybook.user %}
      <a class="btns" href="{% url 'mybooks:favourite' mybook.id %}">
        <i class="fa-solid fa-heart-circle-xmark"></i> Remove from Favourites
      </a>
      {% endif %} {% else %} {% if user == mybook.user %}
      <br />
      <a class="btns mt-2" href="{% url 'mybooks:favourite' mybook.id %}">
        <i class="fa-solid fa-heart-circle-plus"></i> Add to Favourites
      </a>
      {% endif %} {% endif %}
    </div>
    <div>
      <h2><i class="fa-solid fa-book-open"></i> Summary</h2>
      {% if mybook.book.summary %}
      <p>{{ mybook.summary }}</p>
      {% else %}
      <p>No summary yet.</p>
      {% endif %} {% if user == mybook.user %}
      <a class="btns" data-hx-get="{% url 'mybooks:update-summary' mybook.id %}" data-hx-target="#dialog">Edit Summary
      </a>
      {% endif %}
    </div>
  </div>
  <div class="col-12 col-md-4 book-shadow p-0">
    <div class="m-3">
      <h2><i class="fa-solid fa-book-open"></i> Reading Status</h2>
      <!-- If unread -->
      {% if mybook.number_of_times_read == 0 and unread %}
      <p>Unread</p>
      {% if user == mybook.user and not mybook.currently_reading %}
      <a class="btns mb-2" data-hx-get="{% url 'mybooks:start' mybook.id %}" data-hx-target="#dialog">
        Start
      </a>
      {% endif %} {% else %}
      <p>Number of times read: {{ mybook.number_of_times_read }}</p>
      {% endif %}

      <!-- If currently reading-->
      {% if mybook.currently_reading %}
      <p>Currently reading</p>
      <p>Started reading on: {{ mybook.started_reading_on }}</p>
      {% if user == mybook.user %}
      <a class="btns mb-2" data-hx-get="{% url 'mybooks:finish' mybook.id %}" data-hx-target="#dialog">
        Finish
      </a>
      <br>
      <a class="btns mb-2" data-hx-get="{% url 'mybooks:abandon' mybook.id %}" data-hx-target="#dialog">
        Abandon
      </a>
      {% endif %} {% endif %}

      <!-- If finished -->
      {% if mybook.finished %}
      <p>Finished reading</p>
      <p>Finished reading on: {{ mybook.finished_reading_on }}</p>
      {% if user == mybook.user %}
      <a class="btns mb-2" data-hx-get="{% url 'mybooks:start' mybook.id %}" data-hx-target="#dialog">
        Restart
      </a>
      {% endif %} {% endif %}

      <!-- If abandoned -->
      {% if mybook.abandoned %}
      <p>Abandoned</p>
      {% if user == mybook.user %}
      <a class="btns mb-2" data-hx-get="{% url 'mybooks:start' mybook.id %}" data-hx-target="#dialog">
        Restart
      </a>
      {% endif %} {% endif %}
    </div>
    <hr />
    <div class="m-3">
      <h3><i class="fa-solid fa-bars-progress"></i> Progress</h3>
      <p>Pages Total: {{ mybook.pages_total }}</p>
      <p>Pages Read: {{ mybook.pages_read }}</p>
      <p>Percentage Read: {{ mybook.percentage_read }}%</p>
      {% if user == mybook.user %}
      <a class="btns" data-hx-get="{% url 'mybooks:update-progress' mybook.id %}" data-hx-target="#dialog">Update
        Progress</a>
      {% endif %}
    </div>
    <hr />
    <div class="m-3">
      <h3><i class="fa-solid fa-note-sticky"></i> Notes</h3>
      {% if mybook.notes %}
      <p>{{ mybook.notes }}</p>
      {% else %}
      <p>No notes yet.</p>
      {% endif %} {% if user == mybook.user %}
      <a class="btns" data-hx-get="{% url 'mybooks:update-notes' mybook.id %}" data-hx-target="#dialog">Update Notes
      </a>
      {% endif %}
    </div>
    <hr />
    <div class="m-3">
      <h3><i class="fa-solid fa-eye-slash"></i> Visibility</h3>
      {% if mybook.private %}
      <p>Private</p>
      <a class="btns" href="{% url 'mybooks:private' mybook.id %}">Make Visible</a>
      {% else %}
      <p>Visible on your shelf to other users.</p>
      <a class="btns" href="{% url 'mybooks:private' mybook.id %}">Hide</a>
      {% endif %}
    </div>
  </div>
</section>
<section class="container">
  {% if myreview %}
  <!-- This is where the review would go -->
  {% if user != myreview.user and myreview.private %}
  <div>
    <p>{{ myreview.user}}'s review is private.</p>
  </div>
  {% else %}
  <div>
    <h2>My Review</h2>
    <p>{{ myreview.review }}</p>
    <p>Rating: {{ myreview.rating }} / 10</p>
    <p>Posted On: {{ myreview.date_added }}</p>
    {% if user == mybook.user %}
    <a class="btns" data-hx-get="{% url 'review:edit-review' myreview.id %}" data-hx-target="#dialog">Edit Review</a>
    <a class="btns-cancel" href="{% url 'review:delete-review' myreview.id %}">Delete Review</a>
    {% endif %}
  </div>
  {% endif %} {% else %}
  <a class="btns" data-hx-get="{% url 'review:add-review' mybook.book.id %}" data-hx-target="#dialog">Add Review</a>
  {% endif %}
</section>
{% endblock %}
<!-- Modal JS-->
{% block extra_js %}
<script src="{% static 'js/modal.js' %}"></script>
{% endblock %}